Repository cms-gem-daq-project/sw_utils, pull requests merged in 2019-03, with the labels that each got.

#21 Bringing Master even with Develop
  .gitignore
  profiles/gem904daq01/.aliases
  profiles/gem904daq01/.bash_profile
  profiles/gem904daq01/.bashrc
  profiles/gem904qc8daq/.aliases
  profiles/gem904qc8daq/.bash_profile
  profiles/gem904qc8daq/.bashrc
  scripts/autoLatScan.sh
  scripts/calibrateArmDac.sh
  scripts/runLDQM.sh
  scripts/setup_gemdaq.sh
  scripts/setup_only_gem_reg.sh
  v3ElectronicsUserGuide.md
Labels: PR: unreviewed

#22 Update v3ElectronicsUserGuide.md
  v3ElectronicsUserGuide.md
Labels: PR: reviewed-approved

#23 Updated Table of Contents of v3 Guide & Machine Profiles
  README.md
  profiles/gem904qc8daq/.aliases
  profiles/gem904qc8daq/.bash_profile
  v3ElectronicsUserGuide.md
Labels: PR: unreviewed

#24 New Feature: added build instructions for gem-plotting-tools
  v3ElectronicsUserGuide.md
Labels: PR: unreviewed

#26 [WIP] New Feature: adding a script for calibration VThreshold1 of VFAT2
  scripts/calibrateVThreshold1DAC.sh
Labels: enhancement
