Repository cms-gem-daq-project/sw_utils, pull requests merged in 2019-04, with the labels that each got.

#28 New Feature: added option to change starting step for doQC7.sh
  scripts/doQC7.sh
Labels: PR: unreviewed, enhancement

#29 New Feature: dropping debugging flag from QC7 routine
  scripts/doQC7.sh
Labels: PR: unreviewed

#30 added scandate to output ls
  scripts/doQC7.sh
Labels: PR: unreviewed

#31 New Feature: user can now provide geographic address
  scripts/doQC7.sh
Labels: PR: unreviewed, enhancement

#19 Use a time-stamped folder for most log files and output data from calibrateArmDac.sh
  scripts/calibrateArmDac.sh
Labels: PR: reviewed-approved
